name: Current version
description: Extract current branch version from git tags
author: Carlos Prado
branding:
  icon: tag
  color: blue
inputs:
  VERSION_TAG_PREFIX:
    description: git tag prefix for versions
    required: false
    default: "v"
outputs:
  version:
    description: The version string
    value: ${{ steps.version.outputs.version }}
  major:
    description: The version major number
    value: ${{ steps.version.outputs.major }}
  minor:
    description: The version minor number
    value: ${{ steps.version.outputs.minor }}
  patch:
    description: The version patch number
    value: ${{ steps.version.outputs.patch }}
  extra:
    description: Optional version extra parts
    value: ${{ steps.version.outputs.extras }}
  tag:
    description: Optional version tag
    value: ${{ steps.version.outputs.tag }}
runs:
  using: composite
  steps:
    - id: version
      shell: bash
      run: |
        source $(readlink -f $GITHUB_ACTION_PATH/../lib/base.sh)
        LAST_VERSION=$(git_last_version_from_tags)
        set_output version "${LAST_VERSION}"
        set_output major "$(version_major $LAST_VERSION)"
        set_output minor "$(version_minor $LAST_VERSION)"
        set_output patch "$(version_patch $LAST_VERSION)"
        set_output extras "$(version_extras $LAST_VERSION)"
        set_output tag "$(version_tag $LAST_VERSION)"
